// client/vue-client/src/views/Profile.vue
<template>
  <div class="container" v-if="!loading">
    <div class="row">
      <form class="col s6" @submit.prevent="submitHandler">
        <div class="image">
          <img class="materialboxed" width="200"
               :src="imagePreview" alt="profile"/>
        </div>
        <div class="file-field input-field">
          <div class="btn">
            <span>File</span>
            <input type="file"
                   @change="imageHandler"/>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path" type="text"/>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <input type="text"
                   placeholder="Username"
                   v-model="userName"
                   name="userName"/>
          </div>
        </div>
        <button class="btn" type="submit">Save</button>
      </form>
    </div>
  </div>

  <Spinner v-else/>
</template>

<script>

import Spinner from '../components/Spinner'

export default {
  data: () => ({
    userName: '',
    imagePreview: '',
    image: null,
    loading: false
  }),
  methods: {
    imageHandler(e) {
      if(e.target.files && e.target.files[0]) {
        const reader = new FileReader()
        this.image = e.target.files[0]
        reader.onload = (e) => {
          this.imagePreview = e.target.result
        }
        reader.readAsDataURL(e.target.files[0])
      }
    },
    async submitHandler() {
      this.loading = true
      await this.$store.dispatch('editUser', {
        userName: this.userName,
        image: this.image
      })
      this.loading = false
    }
  },
  components: {
    Spinner
  },
  watch: {
    user() {
      this.userName = this.user.userName
      this.imagePreview = this.user.imageUrl
    }
  },
  computed: {
    user() {
      return this.$store.getters.profile
    }
  },
  mounted() {
    const user = this.$store.getters.profile
    this.userName = user.userName
    this.imagePreview = user.imageUrl
  }
}
</script>

<style scoped>
.image {
  margin-top: 2rem;
}

.file-path-wrapper {
  width: 20rem !important;
}

.input-field {
  width: 25rem !important;
}

img {
  border-radius: 5px;
}
</style>

// client/angular-client/src/app/pages/profile/profile.component.ts
import {Component} from '@angular/core'
import {ActionsSubject, select, Store} from '@ngrx/store'
import * as fromAuth from '../../selectors/auth.selectors'
import {edit, editSuccess} from '../../actions/auth.actions'
import {ofType} from '@ngrx/effects'
import {NotifierService} from 'angular-notifier'

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent {

  loading
  userName
  image
  imagePreview
  auth$

  constructor(private store: Store,
              private actionsSubj: ActionsSubject,
              private notifier: NotifierService) {
    this.actionsSubj.pipe(
      ofType(editSuccess)
    ).subscribe(() => {
      this.notifier.notify('success', 'Edit complete')
      this.loading = false
    })
    this.auth$ = store.pipe(select(fromAuth.selectAuth))
    this.auth$.subscribe(data => {
      this.userName = data.userName
      this.imagePreview = data.imageUrl
    })
  }

  submitHandler(e) {
    e.preventDefault()
    this.loading = true
    this.store.dispatch(edit({
      userName: this.userName,
      image: this.image
    }))
  }

  imageHandler(e) {
    const reader = new FileReader()
    if(e.target.files && e.target.files[0]) {
      this.image = e.target.files[0]
      reader.onload = (e) => {
        this.imagePreview = e.target.result
      }
      reader.readAsDataURL(e.target.files[0])
    }
  }

}

<div class="container" *ngIf="!loading;else load">
  <div class="row">
    <form class="col s6" (ngSubmit)="submitHandler($event)">
      <div class="image">
        <img class="materialboxed" width="200"
             [src]="imagePreview"/>
      </div>
      <div class="file-field input-field">
        <div class="btn">
          <span>File</span>
          <input type="file"
                 (change)="imageHandler($event)"/>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path" type="text"/>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <input type="text"
                 placeholder="Username"
                 [(ngModel)]="userName"
                 name="userName"/>
        </div>
      </div>
      <button class="btn" type="submit">Save</button>
    </form>
  </div>
</div>

<ng-template #load>
  <app-spinner></app-spinner>
</ng-template>
