// client/react-client/src/pages/Auth/Auth.js
import React, {createRef, useEffect, useState} from 'react'
import {LoginForm} from '../../components/LoginForm/LoginForm'
import {RegisterForm} from '../../components/RegisterForm/RegisterForm'
import './Auth.css'
import MaterializeService from '../../shared/MaterializeService'
import {connect} from 'react-redux'
import {login, register} from '../../actions'
import {useToasts} from 'react-toast-notifications'

export const AuthPage = connect()(({dispatch}) => {

    const [loading, setLoading] = useState(false)
    const tabs = createRef()

    const {addToast} = useToasts()

    useEffect(() => {
      MaterializeService.initTabs(tabs.current)
    }, [])

    const registerHandler = (data) => {
      setLoading(true)
      dispatch(register(data))
        .then(_ => {
          },
          e => {
            setLoading(false)
            addToast(e.message || 'Error', {
                appearance: 'error',
                autoDismiss: true,
                autoDismissTimeout: 3000
              }
            )
          })
    }

    const loginHandler = (data) => {
      setLoading(true)
      dispatch(login(data))
        .then(_ => {
          },
          e => {
            setLoading(false)
            addToast(e.message || 'Error', {
                appearance: 'error',
                autoDismiss: true,
                autoDismissTimeout: 3000
              }
            )
          })
    }

    return (
      <div className="row">
        <div className="col s12">
          <ul className="tabs" ref={tabs}>
            <li className="tab col s6"><a className="active" href="#login">Login</a></li>
            <li className="tab col s6"><a href="#register">Register</a></li>
          </ul>
        </div>
        <div id="login" className="col s12">
          <LoginForm loading={loading} onLogin={loginHandler}/>
        </div>
        <div id="register" className="col s12">
          <RegisterForm loading={loading} onRegister={registerHandler}/>
        </div>
      </div>
    )
  }
)

// client/angular-client/src/app/pages/auth/auth.component.ts
import {
  AfterViewInit, Component,
  ElementRef, OnDestroy, ViewChild
} from '@angular/core'
import MaterializeService from '../../shared/classes/MaterializeService'
import {Store} from '@ngrx/store'
import {login, loginFailure, loginSuccess, register, registerFailure, registerSuccess} from '../../actions/auth.actions'
import {ActionsSubject} from '@ngrx/store'
import {ofType} from '@ngrx/effects'
import {Subscription} from 'rxjs'
import {NotifierService} from 'angular-notifier'
import {Router} from '@angular/router'

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.css']
})
export class AuthComponent implements AfterViewInit, OnDestroy {

  loading
  @ViewChild('tabs') tabs: ElementRef
  subsc = new Subscription()

  constructor(private store: Store,
              actionSubj: ActionsSubject,
              private notifier: NotifierService,
              private router: Router) {
    this.subsc = actionSubj.pipe(
      ofType(loginFailure, registerFailure)
    ).subscribe(data => {
      this.notifier.notify('success', data.message || 'Error')
      this.loading = false
    })
    actionSubj.pipe(
      ofType(loginSuccess, registerSuccess)
    ).subscribe(() => {
      this.router.navigate(['/todos'])
    })
  }

  loginHandler(data) {
    this.loading = true
    this.store.dispatch(login(data))
  }

  registerHandler(data) {
    this.loading = true
    this.store.dispatch(register(data))
  }

  ngAfterViewInit(): void {
    MaterializeService.initTabs(this.tabs)
  }

  ngOnDestroy(): void {
    this.subsc.unsubscribe()
  }

}

<div class="row">
  <div class="col s12">
    <ul class="tabs" #tabs>
      <li class="tab col s6"><a class="active" href="#login">Login</a></li>
      <li class="tab col s6"><a href="#register">Register</a></li>
    </ul>
  </div>
  <div id="login" class="col s12">
    <app-login-form
        [loading]=loading (onLogin)="loginHandler($event)">
    </app-login-form>
  </div>
  <div id="register" class="col s12">
    <app-register-form
        [loading]=loading (onRegister)="registerHandler($event)">
    </app-register-form>
  </div>
</div>
