// client/angular-client/src/app/components/edit-modal/edit-modal.component.ts
import {
  AfterViewInit, Component, ElementRef, Input,
  Output, ViewChild, EventEmitter, OnInit
} from '@angular/core'
import MaterializeService, {MaterialInstance} from '../../shared/classes/MaterializeService'

@Component({
  selector: 'app-edit-modal',
  templateUrl: './edit-modal.component.html',
  styleUrls: ['./edit-modal.component.css']
})
export class EditModalComponent implements AfterViewInit, OnInit {

  @Input('todoText') todoText
  @Output() onEditFinish = new EventEmitter()
  @ViewChild('input') input: ElementRef
  @ViewChild('modalRef') modalRef: ElementRef
  modal: MaterialInstance
  text

  onFinishCancel() {
    this.onEditFinish.emit({
      status: 'cancel'
    })
    this.modal.close()
  }

  onFinishConfirm() {
    if(this.text.trim()) {
      this.onEditFinish.emit({
        status: 'ok',
        text: this.text
      })
      this.modal.close()
    }
  }

  keyHandler(e) {
    if(e.key === 'Enter') {
      this.onFinishConfirm()
    }
  }

  ngAfterViewInit(): void {
    this.input.nativeElement.focus()
    this.modal = MaterializeService.initModal(this.modalRef)
    this.modal.open()
  }

  ngOnInit(): void {
    this.text = this.todoText
  }

}

<div id="modal" class="modal" #modalRef>
  <div class="modal-content">
    <div class="input-field">
      <input type="text" value={text}
             [(ngModel)]="text"
             (keydown)="keyHandler($event)"
             #input/>
    </div>
  </div>
  <div class="modal-footer">
    <button
        (click)="onFinishCancel()"
        class="btn waves-effect waves-green btn-flat">
      Cancel
    </button>
    <button
        (click)="onFinishConfirm()"
        class="btn waves-effect waves-green btn-flat">
      Ok
    </button>
  </div>
</div>

// client/react-client/src/components/EditModal/EditModal.js
import React, {createRef, useEffect, useRef, useState} from 'react'
import MaterializeService from '../../shared/MaterializeService'
import './EditModal.css'

export const EditModal = ({onEditFinish, todoText}) => {

  const [text, setText] = useState(todoText)
  const modalRef = useRef()
  let modal
  const input = createRef()

  useEffect(() => {
    modal = MaterializeService.initModal(modalRef.current)
    modal.open()
    input.current.focus()
  }, [])

  const onFinishConfirm = () => {
    if(text.trim()) {
      if(modal) {
        modal.close()
      }
      onEditFinish({
        status: 'ok',
        text
      })
    }
  }

  const keyHandler = ({key}) => {
    if(key === 'Enter') {
      onFinishConfirm()
    }
  }

  const onFinishCancel = () => {
    if(modal) {
      modal.close()
    }
    onEditFinish({status: 'cancel'})
  }

  return (
    <div id="modal" className="modal" ref={modalRef}>
      <div className="modal-content">
        <div className="input-field">
          <input type="text" value={text}
                 onChange={({target: {value}}) => {
                   setText(value)
                 }}
                 onKeyDown={keyHandler}
                 ref={input}/>
        </div>
      </div>
      <div className="modal-footer">
        <button
          onClick={onFinishCancel}
          className="btn waves-effect waves-green btn-flat">
          Cancel
        </button>
        <button
          onClick={onFinishConfirm}
          className="btn waves-effect waves-green btn-flat">
          Ok
        </button>
      </div>
    </div>
  )
}
