// client/react-client/src/App.js
import React from 'react'
import {Provider} from 'react-redux'
import {ToastProvider} from 'react-toast-notifications'
import initStore from './store'
import {BrowserRouter as Router} from 'react-router-dom'
import TodosApp from './TodosApp'
import {loginFromStore} from './actions'

const store = initStore()

class App extends React.Component {

  componentDidMount() {
    store.dispatch(loginFromStore())
  }

  render() {
    return (
      <Provider store={store}>
        <ToastProvider>
          <Router>
            <TodosApp/>
          </Router>
        </ToastProvider>
      </Provider>
    )
  }
}

export default App

// client/vue-client/src/App.vue
<template>
  <div id="app">
    <Navbar/>
    <div class="container">
      <router-view/>
    </div>
    <notifications/>
  </div>
</template>

<script>

import Navbar from '@/components/Navbar'

export default {
  mounted() {
    this.$store.dispatch('loginFromStore')
  },
  components: {
    Navbar
  }
}
</script>
