// client/angular-client/src/app/components/login-form/login-form.component.ts
import {Component, Input, OnInit, Output, EventEmitter} from '@angular/core'
import {FormControl, FormGroup, Validators} from '@angular/forms'

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.css']
})
export class LoginFormComponent implements OnInit {

  @Output() onLogin = new EventEmitter()
  @Input() loading
  form: FormGroup

  constructor() {
  }

  ngOnInit(): void {
    this.form = new FormGroup({
      email: new FormControl('', Validators.required),
      password: new FormControl('', Validators.required)
    })
  }

  onSubmit(e) {
    e.preventDefault()
    this.onLogin.emit(this.form.value)
  }

}

<div class="row">
  <form class="col s12" [formGroup]="form" (ngSubmit)="onSubmit($event)">
    <div class="row">
      <div class="input-field">
        <i class="material-icons prefix">alternate_email</i>
        <input id="email_l" type="text"
               name="email"
               formControlName="email"/>
        <label for="email_l">Email</label>
        <span *ngIf="form.get('email').invalid&&
form.get('email').touched"
              class="helper-text red-text">Email is required</span>
      </div>
      <div class="input-field">
        <i class="material-icons prefix">vpn_key</i>
        <input id="password_l" type="password"
               name="password"
               formControlName="password"/>
        <label for="password_l">Password</label>
        <span *ngIf="form.get('password').invalid&&
form.get('password').touched"
              class="helper-text red-text">Password is required</span>
      </div>
      <div class="input-field">
        <button class="btn"
                [disabled]="loading||form.invalid"
                type="submit"
        >Login
        </button>
      </div>
    </div>
  </form>
</div>

// client/react-client/src/components/LoginForm/LoginForm.js
import React from 'react'
import {useForm} from 'react-hook-form'

export const LoginForm = ({onLogin, loading}) => {

  const {register, handleSubmit, errors} = useForm()

  const submitHandler = (data) => {
    onLogin(data)
  }

  return (
    <div className="row">
      <form className="col s12" onSubmit={handleSubmit(submitHandler)}>
        <div className="row">
          <div className="input-field">
            <i className="material-icons prefix">alternate_email</i>
            <input id="email_l" type="text"
                   name="email"
                   ref={register({required: true})}/>
            <label htmlFor="email_l">Email</label>
            {
              errors.email &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Email is required</span>
            }
          </div>
          <div className="input-field">
            <i className="material-icons prefix">vpn_key</i>
            <input id="password_l" type="password"
                   name="password"
                   ref={register({required: true})}/>
            <label htmlFor="password_l">Password</label>
            {
              errors.password &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Password is required</span>
            }
          </div>
          <div className="input-field">
            <button className="btn"
                    disabled={loading}
                    type="submit"
            >Login
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
