// client/vue-client/src/components/LoginForm.vue
<template>
  <div class="row">
    <form class="col s12" @submit.prevent="submitHandler">
      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">alternate_email</i>
          <input id="email_l" type="text"
                 name="email"
                 v-model="email"/>
          <label for="email_l">Email</label>
          <span v-if="$v.email.$dirty&&!$v.email.required"
                class="helper-text red-text">Email is required</span>
        </div>
        <div class="input-field">
          <i class="material-icons prefix">vpn_key</i>
          <input id="password_l" type="password"
                 name="password"
                 v-model="password"/>
          <label for="password_l">Password</label>
          <span v-if="$v.password.$dirty&&!$v.password.required"
                class="helper-text red-text">Password is required</span>
        </div>
        <div class="input-field">
          <button class="btn"
                  :disabled="loading"
                  type="submit"
          >Login
          </button>
        </div>
      </div>
    </form>
  </div>
</template>

<script>

import {required} from 'vuelidate/lib/validators'

export default {
  name: 'LoginForm',
  data: () => ({
    email: '',
    password: '',
    loading: false
  }),
  validations: {
    email: {required},
    password: {required}
  },
  methods: {
    async submitHandler() {
      if(this.$v.$invalid) {
        this.$v.$touch()
        return
      }
      this.loading = true
      this.$store.dispatch('login', {
        email: this.email,
        password: this.password
      }).catch(err => {
        this.$notify({
          text: err.message || 'Error',
          type: 'error',
          duration: 3000
        })
        this.loading = false
      })
    }
  }
}
</script>

<style scoped>

</style>

// client/react-client/src/components/LoginForm/LoginForm.js
import React from 'react'
import {useForm} from 'react-hook-form'

export const LoginForm = ({onLogin, loading}) => {

  const {register, handleSubmit, errors} = useForm()

  const submitHandler = (data) => {
    onLogin(data)
  }

  return (
    <div className="row">
      <form className="col s12" onSubmit={handleSubmit(submitHandler)}>
        <div className="row">
          <div className="input-field">
            <i className="material-icons prefix">alternate_email</i>
            <input id="email_l" type="text"
                   name="email"
                   ref={register({required: true})}/>
            <label htmlFor="email_l">Email</label>
            {
              errors.email &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Email is required</span>
            }
          </div>
          <div className="input-field">
            <i className="material-icons prefix">vpn_key</i>
            <input id="password_l" type="password"
                   name="password"
                   ref={register({required: true})}/>
            <label htmlFor="password_l">Password</label>
            {
              errors.password &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Password is required</span>
            }
          </div>
          <div className="input-field">
            <button className="btn"
                    disabled={loading}
                    type="submit"
            >Login
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
