// client/angular-client/src/app/components/todo-list-item/todo-list-item.component.ts
import {Component, Input} from '@angular/core'
import {select, Store} from '@ngrx/store'
import {
  changeOpen,
  deleteTodos,
  edit,
  markExecuted,
  markStared
} from '../../actions/todos.actions'
import {Todo} from '../../shared/interfaces'
import {createIdsArray} from '../../helpers/array.helper'
import * as fromTodo from '../../selectors/todo.selector'

@Component({
  selector: 'app-todo-list-item',
  templateUrl: './todo-list-item.component.html',
  styleUrls: ['./todo-list-item.component.css']
})
export class TodoListItemComponent {

  @Input('todo') todo: Todo

  isSearch = false
  isCreating
  isEdit
  todos$

  constructor(private store: Store) {
    this.todos$ = store.pipe(select(fromTodo.selectTodos))
    this.todos$.subscribe(data => {
      this.isSearch = data.isSearch
    })
  }

  execHandler() {
    this.store.dispatch(markExecuted({
      id: this.todo.id,
      executed: !this.todo.executed
    }))
  }

  starHandler() {
    this.store.dispatch(markStared({
      id: this.todo.id,
      stared: !this.todo.stared
    }))
  }

  deleteHandler() {
    if(window.confirm('Delete this todo?')) {
      this.store.dispatch(deleteTodos({
        parent: this.todo.id,
        idsToDelete: [this.todo.id, ...createIdsArray(this.todo.todos)]
      }))
    }
  }

  openHandler() {
    this.store.dispatch(changeOpen({
      id: this.todo.id,
      isOpen: !this.todo.isOpen
    }))
  }

  createTodoHandler() {
    this.isCreating = !this.isCreating
  }

  onEditFinish(result) {
    if(result.status === 'ok') {
      this.store.dispatch(edit({
        id: this.todo.id,
        text: result.text
      }))
    }
  }

  editHandler() {
    this.isEdit = !this.isEdit
  }

}

<div class="todo-container">
  <div class="todo-item">
    <i class="material-icons prefix edit"
       (click)="editHandler()"
    >mode_edit</i>
    <div class="todo-item-text">
      {{todo.text}}
    </div>
    <div *ngIf="todo.executed" class="executed"></div>
    <div class="todo-item-actions">
      <p>
        <label>
          <input type="checkbox"
                 [checked]="todo.executed"
                 (change)="execHandler()"
          />
          <span></span>
        </label>
      </p>
      <i class="material-icons prefix star"
         [ngClass]="{ 'stared':todo.stared }"
         (click)="starHandler()">
        {{todo.stared ? 'star' : 'star_border'}}
      </i>
      <i *ngIf="!isSearch" class="material-icons prefix delete"
         (click)="deleteHandler()"
      >
        delete
      </i>
    </div>
    <i *ngIf="todo.todos.length>0&&!isSearch" class="material-icons open"
       (click)="openHandler()"
    >
      keyboard_arrow_down
    </i>
    <i *ngIf="!isSearch" class="material-icons add"
       (click)="createTodoHandler()"
    >
      add
    </i>
  </div>

  <div class="next" *ngIf="isCreating">
    <app-todo-form [parent]="todo.id">
    </app-todo-form>
  </div>
  <div class="next" *ngIf="todo.isOpen">
    <app-todo-list [todos]="todo.todos">
    </app-todo-list>
  </div>
  <app-edit-modal *ngIf="isEdit"
                  [todoText]="todo.text"
                  (onEditFinish)="onEditFinish($event)"
  ></app-edit-modal>
</div>

// client/react-client/src/components/TodoListItem/TodoListItem.js
import React, {useState} from 'react'
import './TodoListItem.css'
import {TodoList} from '../TodosList/TodosList'
import {TodoForm} from '../TodoForm/TodoForm'
import {connect} from 'react-redux'
import {changeOpen, deleteTodo, editTodo, markExecuted, markStared} from '../../actions'
import {EditModal} from '../EditModal/EditModal'
import {createIdsArray} from '../../helpers/array.helper'
import {useToasts} from 'react-toast-notifications'

const mapStateToProps = ({todos: {isSearch}}) => ({isSearch})

export const TodoListItem = connect(mapStateToProps)
(({todo, dispatch, isSearch}) => {

    const [isCreating, setCreate] = useState(false)
    const [isEdit, setEdit] = useState(false)

    const {addToast} = useToasts()

    const openHandler = () => {
      dispatch(changeOpen(todo.id, !todo.isOpen))
    }

    const createTodoHandler = () => {
      setCreate(!isCreating)
    }

    const starHandler = () => {
      dispatch(markStared(todo.id, !todo.stared))
        .then(() => {
          addToast('Stared complete', {
              appearance: 'success',
              autoDismiss: true,
              autoDismissTimeout: 1000
            }
          )
        })
    }

    const execHandler = ({target: {checked}}) => {
      dispatch(markExecuted(todo.id, checked))
        .then(() => {
          addToast('Executed complete', {
              appearance: 'success',
              autoDismiss: true,
              autoDismissTimeout: 1000
            }
          )
        })
    }

    const deleteHandler = () => {
      if(window.confirm(`Delete this todo ${todo.todos.length ? 'and all branches ' : ''}?`)) {
        dispatch(deleteTodo(todo.id,
          [todo.id, ...createIdsArray(todo.todos)]))
      }
    }

    const editHandler = () => {
      setEdit(!isEdit)
    }

    const onEditFinish = (result) => {
      setEdit(false)
      if(result.status === 'ok' && todo.text !== result.text) {
        dispatch(editTodo(todo.id, result.text))
          .then(() => {
            addToast('Edit complete', {
                appearance: 'success',
                autoDismiss: true,
                autoDismissTimeout: 1000
              }
            )
          })
      }
    }

    return (
      <div className="todo-container">
        <div className="todo-item">
          <i className="material-icons prefix edit"
             onClick={editHandler}
          >mode_edit</i>
          <div className="todo-item-text">
            {todo.text}
          </div>
          {
            todo.executed &&
            <div className="executed"></div>
          }
          <div className="todo-item-actions">
            <p>
              <label>
                <input type="checkbox" checked={todo.executed}
                       onChange={execHandler}
                />
                <span></span>
              </label>
            </p>
            <i className={`material-icons prefix star 
        ${todo.stared ? 'stared' : ''}`}
               onClick={starHandler}
            >
              {todo.stared ? 'star' : 'star_border'}
            </i>
            {
              !isSearch &&
              <i className="material-icons prefix delete"
                 onClick={deleteHandler}
              >
                delete
              </i>
            }
          </div>
          {
            todo.todos.length > 0 && !isSearch &&
            <>
              <i className="material-icons open"
                 onClick={openHandler}
              >
                keyboard_arrow_down
              </i>
            </>
          }
          {
            !isSearch &&
            <i className="material-icons add"
               onClick={createTodoHandler}
            >
              add
            </i>
          }
        </div>
        {
          isCreating &&
          <div className="next">
            <TodoForm parent={todo.id}/>
          </div>
        }
        {
          todo.isOpen &&
          <div className="next">
            <TodoList todos={todo.todos}/>
          </div>
        }
        {
          isEdit &&
          <EditModal todoText={todo.text} onEditFinish={onEditFinish}/>
        }
      </div>
    )
  }
)
