// client/angular-client/src/app/components/register-form/register-form.component.ts
import {Component, Input, OnInit, Output, EventEmitter} from '@angular/core'
import {FormControl, FormGroup, Validators} from '@angular/forms'

@Component({
  selector: 'app-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.css']
})
export class RegisterFormComponent implements OnInit {

  @Output() onRegister = new EventEmitter()
  @Input() loading
  form: FormGroup

  constructor() {
  }

  ngOnInit(): void {
    this.form = new FormGroup({
      email: new FormControl('', Validators.required),
      password: new FormControl('',
        [Validators.required, Validators.minLength(6)]),
      userName: new FormControl('', Validators.required)
    })
  }

  onSubmit(e) {
    e.preventDefault()
    this.onRegister.emit(this.form.value)
  }

}

<div class="row">
  <form class="col s12" [formGroup]="form" (ngSubmit)="onSubmit($event)">
    <div class="row">
      <div class="input-field">
        <i class="material-icons prefix">account_circle</i>
        <input id="username" type="text"
               name="userName"
               formControlName="userName"/>
        <label for="username">Username</label>
        <span class="helper-text red-text"
              *ngIf="form.get('userName').invalid&&
form.get('userName').touched"
              data-error="wrong"
              data-success="right">Username is required</span>
      </div>
      <div class="input-field">
        <i class="material-icons prefix">alternate_email</i>
        <input id="email_r" type="text"
               name="email"
               formControlName="email"/>
        <label for="email_r">Email</label>
        <span class="helper-text red-text"
              *ngIf="form.get('email').invalid&&
form.get('email').touched"
              data-error="wrong"
              data-success="right">Email is required</span>
      </div>
      <div class="input-field">
        <i class="material-icons prefix">vpn_key</i>
        <input id="password_r" type="password"
               name="password"
               formControlName="password"/>
        <label class="password_r">Password</label>
        <span class="helper-text red-text"
              *ngIf="form.get('password').invalid&&
form.get('password').touched">
          <span class="helper-text red-text"
                *ngIf="form.get('password').errors['required']">
            Password is required
        </span>
          <span class="helper-text red-text"
                *ngIf="form.get('password').errors['minlength']">
            Password min length is 6
        </span>
        </span>
      </div>
      <div class="input-field">
        <button class="btn"
                [disabled]="loading||form.invalid"
                type="submit"
        >Register
        </button>
      </div>
    </div>
  </form>
</div>

// client/react-client/src/components/RegisterForm/RegisterForm.js
import React from 'react'
import {useForm} from 'react-hook-form'

export const RegisterForm = ({onRegister, loading}) => {

  const {register, handleSubmit, errors} = useForm()

  const submitHandler = (data) => {
    onRegister(data)
  }

  return (
    <div className="row">
      <form className="col s12" onSubmit={handleSubmit(submitHandler)}>
        <div className="row">
          <div className="input-field">
            <i className="material-icons prefix">account_circle</i>
            <input id="username" type="text"
                   name="userName"
                   ref={register({required: true})}/>
            <label htmlFor="username">Username</label>
            {
              errors.password &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Username is required</span>
            }
          </div>
          <div className="input-field">
            <i className="material-icons prefix">alternate_email</i>
            <input id="email_r" type="text"
                   name="email"
                   ref={register({required: true})}/>
            <label htmlFor="email_r">Email</label>
            {
              errors.email &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Email is required</span>
            }
          </div>
          <div className="input-field">
            <i className="material-icons prefix">vpn_key</i>
            <input id="password_r" type="password"
                   name="password"
                   ref={register({required: true, minLength: 6})}/>
            <label htmlFor="password_r">Password</label>
            {
              errors.password?.type === 'required' &&
              <span className="helper-text" data-error="wrong"
                    data-success="right">Password is required</span>
            }
            {
              errors.password?.type === 'minLength' &&
              <span className="helper-text text-danger" data-error="wrong"
                    data-success="right">Min length is 6</span>
            }
          </div>
          <div className="input-field">
            <button className="btn"
                    disabled={loading}
                    type="submit"
            >Register
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
