// client/angular-client/src/app/components/todo-form/todo-form.component.ts
import {
  AfterViewInit, Component,
  ElementRef, ViewChild, Input
} from '@angular/core'
import {Store} from '@ngrx/store'
import {add} from '../../actions/todos.actions'

@Component({
  selector: 'app-todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.css']
})
export class TodoFormComponent implements AfterViewInit {

  @Input('parent') parent
  @ViewChild('input') input: ElementRef
  text

  constructor(private store: Store) {
  }

  submitHandler(e) {
    if(e.key === 'Enter') {
      if(this.text.trim()) {
        this.store.dispatch(add({
          text: this.text,
          parent: this.parent,
          stared: false
        }))
      }
    }
  }

  ngAfterViewInit(): void {
    this.input.nativeElement.focus()
  }

}

<div class="row form">
  <div class="input-field">
    <input placeholder="Add branch...."
           class="materialize-textarea"
           [(ngModel)]="text"
           (keydown)="submitHandler($event)"
           #input
    />
  </div>
</div>

// client/react-client/src/components/TodoForm/TodoForm.js
import React, {createRef, useEffect, useState} from 'react'
import './TodoForm.css'
import {connect} from 'react-redux'
import {addTodo} from '../../actions'
import {useToasts} from 'react-toast-notifications'

export const TodoForm = connect()(({parent, dispatch}) => {

    const [todoText, setText] = useState('')
    const input = createRef()

    const {addToast} = useToasts()

    const changeHandler = ({target: {value}}) => {
      setText(value)
    }

    useEffect(() => {
      input.current.focus()
    }, [])

    const submitHandler = ({key}) => {
      if(key === 'Enter' && todoText.trim()) {
        dispatch(addTodo({text: todoText, parent}))
          .then(() => {
            addToast('Todo added', {
                appearance: 'success',
                autoDismiss: true,
                autoDismissTimeout: 1000
              }
            )
          })
        setText('')
      }
    }

    return (
      <div className="row form">
        <div className="input-field">
          <input placeholder="Add branch...."
                 className="materialize-textarea"
                 value={todoText}
                 onChange={changeHandler}
                 onKeyDown={submitHandler}
                 ref={input}
          />
        </div>
      </div>
    )
  }
)
