// client/vue-client/src/components/Navbar.vue
<template>
  <nav>
    <div class="nav-wrapper #6a1b9a purple darken-3">
      <div v-if="user.isAuth">
        <ul id="nav-mobile1" class="left">
          <li class="hello"><span>Hi {{ user.userName|capitalize }}</span></li>
        </ul>
      </div>
      <router-link to="/todos">
        <a class="brand-logo center">
          Todos App
        </a>
      </router-link>
      <ul id="nav-mobile" class="right">
        <li v-if="!user.isAuth">
          <router-link to="/">
            <a>Login/Register</a>
          </router-link>
        </li>
        <template v-if="user.isAuth">
          <img :src="user.imageUrl" class="image-profile" alt="profile"/>
          <li>
            <router-link to="/todos">
              <a>Todos</a>
            </router-link>
          </li>
          <li>
            <router-link to="/profile">
              <a>Profile</a>
            </router-link>
          </li>
          <li @click="logout" class="logout">
            <a>Logout</a>
          </li>
        </template>
      </ul>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar',
  computed: {
    user() {
      return this.$store.getters.navbar
    }
  },
  methods: {
    logout() {
      this.$store.dispatch('logout')
    }
  },
  filters: {
    capitalize: function(value) {
      if(!value) return ''
      value = value.toString()
      return value.charAt(0).toUpperCase() + value.slice(1)
    }
  }
}
</script>

<style scoped>
#nav-mobile {
  padding-right: 1.5rem;
  padding-bottom: 1rem;
}

a.active {
  background-color: #5f0e90;
}

button {
  background-color: #8626c1 !important;
}

.hello {
  cursor: pointer;
  margin-left: 2rem;
}

.image-profile {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  position: relative;
  right: 22rem;
  top: 0.8rem;
}
</style>

// client/react-client/src/components/Navbar/Navbar.js
import React from 'react'
import {NavLink, Link} from 'react-router-dom'
import './Navbar.css'
import {upperCaseFirst} from '../../helpers/name.helper'
import {connect} from 'react-redux'
import {logout} from '../../actions'

export const Navbar = connect()
(({isAuth, userName, imageUrl, dispatch}) => {
    return (
      <nav>
        <div className="nav-wrapper #6a1b9a purple darken-3">
          {
            isAuth &&
            <ul id="nav-mobile" className="left">

              <li className="hello"><span>Hi {upperCaseFirst(userName)}</span></li>
            </ul>
          }
          <Link to='/todos' className="brand-logo center">Todos App</Link>
          <ul id="nav-mobile" className="right">
            {
              !isAuth &&
              <li><NavLink to='/'>Login/Register</NavLink></li>
            }
            {
              isAuth &&
              <>
                <img src={imageUrl} className="image-profile" alt="profile"/>
                <li><NavLink to='/todos'>Todos</NavLink></li>
                <li><NavLink to='/profile'>Profile</NavLink></li>
                <li onClick={() => dispatch(logout())} className="logout">
                  <a>Logout</a>
                </li>
              </>
            }
          </ul>
        </div>
      </nav>
    )
  }
)
