// client/angular-client/src/app/components/navbar/navbar.component.ts
import {Component, OnInit} from '@angular/core'
import {select, Store} from '@ngrx/store'
import {reset} from '../../actions/auth.actions'
import {Router} from '@angular/router'
import * as fromAuth from '../../selectors/auth.selectors'

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  auth$
  auth

  constructor(private store: Store<{ auth }>,
              private router: Router) {
    this.auth$ = store.pipe(select(fromAuth.selectAuth))
    this.auth$.subscribe(data => {
      this.auth = data
    })
  }

  ngOnInit(): void {
  }

  logout() {
    this.store.dispatch(reset())
    this.router.navigate([''])
  }

}

<nav>
  <div class="nav-wrapper #6a1b9a purple darken-3">
    <ng-container *ngIf="auth.isAuth">
      <ul id="nav-mobile1" class="left">
        <li class="hello"><span>Hi {{auth.userName|titlecase}}</span></li>
      </ul>
    </ng-container>
    <a routerLink="/todos" class="brand-logo center">
      Todos App</a>
    <ul id="nav-mobile" class="right">
      <li *ngIf="!auth.isAuth">
        <a routerLink="login">Login/Register</a>
      </li>
      <ng-container *ngIf="auth.isAuth">
        <img [src]="auth.imageUrl" class="image-profile" alt="profile"/>
        <li>
          <a routerLink="/todos">Todos</a>
        </li>
        <li>
          <a routerLink="/profile">Profile</a>
        </li>
        <li (click)="logout()" class="logout">
          <a>Logout</a>
        </li>
      </ng-container>
    </ul>
  </div>
</nav>

// client/react-client/src/components/Navbar/Navbar.js
import React from 'react'
import {NavLink, Link} from 'react-router-dom'
import './Navbar.css'
import {upperCaseFirst} from '../../helpers/name.helper'
import {connect} from 'react-redux'
import {logout} from '../../actions'

export const Navbar = connect()
(({isAuth, userName, imageUrl, dispatch}) => {
    return (
      <nav>
        <div className="nav-wrapper #6a1b9a purple darken-3">
          {
            isAuth &&
            <ul id="nav-mobile" className="left">

              <li className="hello"><span>Hi {upperCaseFirst(userName)}</span></li>
            </ul>
          }
          <Link to='/todos' className="brand-logo center">Todos App</Link>
          <ul id="nav-mobile" className="right">
            {
              !isAuth &&
              <li><NavLink to='/'>Login/Register</NavLink></li>
            }
            {
              isAuth &&
              <>
                <img src={imageUrl} className="image-profile" alt="profile"/>
                <li><NavLink to='/todos'>Todos</NavLink></li>
                <li><NavLink to='/profile'>Profile</NavLink></li>
                <li onClick={() => dispatch(logout())} className="logout">
                  <a>Logout</a>
                </li>
              </>
            }
          </ul>
        </div>
      </nav>
    )
  }
)
