// client/vue-client/src/components/TodoMainForm.vue
<template>
  <div class="row">
    <div class="input-field">
      <i class="material-icons prefix">mode_edit</i>
      <input placeholder="Add todo..."
             class="materialize-input"
             v-model="text"
             @keydown="submitHandler"
             :disabled="isSearch"
      />
      <i class="material-icons prefix"
         :class="{'stared':stared}"
         @click="starHandler"
      >
        {{ stared ? 'star' : 'star_border' }}
      </i>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TodoMainForm',
  data: () => ({
    text: '',
    stared: false
  }),
  methods: {
    submitHandler(e) {
      if(e.key === 'Enter') {
        if(this.text.trim()) {
          this.$store.dispatch('add', {
            text: this.text,
            stared: this.stared
          })
          this.text = ''
          this.stared = false
        }
      }
    },
    starHandler() {
      this.stared = !this.stared
    }
  },
  computed: {
    isSearch() {
      return this.$store.getters.isSearch
    }
  }
}
</script>

<style scoped>
.input-field i {
  cursor: pointer;
}

i.stared {
  color: yellow;
}
</style>

// client/angular-client/src/app/components/todo-main-form/todo-main-form.component.ts
import {Component} from '@angular/core'
import {Store} from '@ngrx/store'
import {add} from '../../actions/todos.actions'

@Component({
  selector: 'app-todo-main-form',
  templateUrl: './todo-main-form.component.html',
  styleUrls: ['./todo-main-form.component.css']
})
export class TodoMainFormComponent {

  isSearch
  todo = {
    stared: false,
    text: ''
  }

  constructor(private store: Store) {

  }

  submitHandler(e) {
    if(e.key === 'Enter') {
      if(this.todo.text.trim()) {
        this.store.dispatch(add({...this.todo, parent: null}))
        this.todo.stared = false
        this.todo.text = ''
      }
    }
  }

  starHandler() {
    this.todo.stared = !this.todo.stared
  }

}

<div class="row">
  <div class="input-field">
    <i class="material-icons prefix">mode_edit</i>
    <input placeholder="Add todo..."
           class="materialize-input"
           [(ngModel)]="todo.text"
           (keydown)="submitHandler($event)"
           [disabled]="isSearch"
    />
    <i class="material-icons prefix"
       [ngClass]="{'stared':todo.stared}"
       (click)="starHandler()"
    >
      {{todo.stared?'star':'star_border'}}
    </i>
  </div>
</div>
