// client/vue-client/src/views/Profile.vue
<template>
  <div class="container" v-if="!loading">
    <div class="row">
      <form class="col s6" @submit.prevent="submitHandler">
        <div class="image">
          <img class="materialboxed" width="200"
               :src="imagePreview" alt="profile"/>
        </div>
        <div class="file-field input-field">
          <div class="btn">
            <span>File</span>
            <input type="file"
                   @change="imageHandler"/>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path" type="text"/>
          </div>
          <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <input type="text"
                   placeholder="Username"
                   v-model="userName"
                   name="userName"/>
          </div>
        </div>
        <button class="btn" type="submit">Save</button>
      </form>
    </div>
  </div>

  <Spinner v-else/>
</template>

<script>

import Spinner from '../components/Spinner'

export default {
  data: () => ({
    userName: '',
    imagePreview: '',
    image: null,
    loading: false
  }),
  methods: {
    imageHandler(e) {
      if(e.target.files && e.target.files[0]) {
        const reader = new FileReader()
        this.image = e.target.files[0]
        reader.onload = (e) => {
          this.imagePreview = e.target.result
        }
        reader.readAsDataURL(e.target.files[0])
      }
    },
    async submitHandler() {
      this.loading = true
      await this.$store.dispatch('editUser', {
        userName: this.userName,
        image: this.image
      })
      this.loading = false
    }
  },
  components: {
    Spinner
  },
  watch: {
    user() {
      this.userName = this.user.userName
      this.imagePreview = this.user.imageUrl
    }
  },
  computed: {
    user() {
      return this.$store.getters.profile
    }
  },
  mounted() {
    const user = this.$store.getters.profile
    this.userName = user.userName
    this.imagePreview = user.imageUrl
  }
}
</script>

<style scoped>
.image {
  margin-top: 2rem;
}

.file-path-wrapper {
  width: 20rem !important;
}

.input-field {
  width: 25rem !important;
}

img {
  border-radius: 5px;
}
</style>

// client/react-client/src/pages/Profile/Profile.js
import React, {useEffect, useState} from 'react'
import * as api from '../../api'
import {Spinner} from '../../components/Spinner/Spinner'
import './Profile.css'
import {useToasts} from 'react-toast-notifications'
import {connect} from 'react-redux'
import {editUser} from '../../actions'

const mapStateToProps = ({auth: {imageUrl, userName}}) =>
  ({imageUrl, userName})

export const ProfilePage = connect(mapStateToProps)
(({imageUrl, userName, dispatch}) => {

    const [user, setUser] = useState({
      image: '',
      userName,
      imagePreview: imageUrl
    })
    const [loading, setLoading] = useState(false)

    const {addToast} = useToasts()

    if(loading) {
      return <Spinner/>
    }

    const userNameHandler = ({target: {value}}) => {
      setUser({...user, userName: value})
    }

    const submitHandler = (e) => {
      e.preventDefault()
      setLoading(true)
      dispatch(editUser(user))
        .then(() => {
          setLoading(false)
          addToast('Information updated', {
              appearance: 'success',
              autoDismiss: true,
              autoDismissTimeout: 2000
            }
          )
        })
    }

    const imageHandler = ({target: {files}}) => {
      const reader = new FileReader()
      reader.onload = function(e) {
        setUser({
          ...user,
          imagePreview: e.target.result,
          image: files[0]
        })
      }
      reader.readAsDataURL(files[0])
    }

    return (
      <div className="container">
        <div className="row">
          <form className="col s6" onSubmit={submitHandler}>
            <div className="image">
              <img className="materialboxed" width="200"
                   src={user.imagePreview}/>
            </div>
            <div className="file-field input-field">
              <div className="btn">
                <span>File</span>
                <input type="file"
                       onChange={imageHandler}/>
              </div>
              <div className="file-path-wrapper">
                <input className="file-path" type="text"/>
              </div>
              <div className="input-field col s6">
                <i className="material-icons prefix">account_circle</i>
                <input type="text"
                       placeholder="Username"
                       onChange={userNameHandler}
                       value={user.userName}/>
              </div>
            </div>
            <button className="btn" type="submit">Save</button>
          </form>
        </div>
      </div>
    )
  }
)
