// client/react-client/src/components/SearchForm/SearchForm.js
import React, {createRef, useEffect, useState} from 'react'
import {connect} from 'react-redux'
import './SearchForm.css'
import {onSearch} from '../../actions'

const mapStateToProps = ({todos: {todos, isSearch}}) =>
  ({todos, isSearch})

export const SearchForm = connect(mapStateToProps)
(({dispatch, todos, isSearch}) => {

    const [text, setSearch] = useState('')

    const changeHandler = ({target: {value}}) => {
      const text = value.trimLeft().toLowerCase()
      setSearch(text)
      dispatch(onSearch(text, [...todos]))
    }

    return (
      <div className="input-field search">
        <input type="text" value={text}
               placeholder="Search items..."
               className="input-search"
               onChange={changeHandler}/>
        <i className={`material-icons search-icon ${isSearch ? 'is-search' : ''}`}>search</i>
      </div>
    )
  }
)

// client/angular-client/src/app/components/search-form/search-form.component.ts
import {Component} from '@angular/core'
import {ActionsSubject, select, Store} from '@ngrx/store'
import {editSuccess, search} from '../../actions/todos.actions'
import {ofType} from '@ngrx/effects'
import * as fromTodo from '../../selectors/todo.selector'

@Component({
  selector: 'app-search-form',
  templateUrl: './search-form.component.html',
  styleUrls: ['./search-form.component.css']
})
export class SearchFormComponent {

  isSearch
  text
  todos$

  constructor(private store: Store<{ todo }>,
              private actionSubj: ActionsSubject) {
    this.todos$ = store.pipe(select(fromTodo.selectTodos))
    this.todos$.subscribe(data => {
      this.isSearch = data.isSearch
    })
    actionSubj.pipe(
      ofType(editSuccess)
    ).subscribe(() => {
      this.store.dispatch(search({text: this.text}))
    })
  }

  changeHandler(text) {
    this.store.dispatch(search({text}))
  }

}

<div class="input-field search">
  <input type="text" [(ngModel)]="text"
         placeholder="Search items..."
         class="input-search"
         (ngModelChange)="changeHandler($event)"/>
  <i class="material-icons search-icon"
     [ngClass]="{ 'is-search':isSearch }"
  >search</i>
</div>
