// client/angular-client/src/app/components/todo-form/todo-form.component.ts
import {
  AfterViewInit, Component,
  ElementRef, ViewChild, Input
} from '@angular/core'
import {Store} from '@ngrx/store'
import {add} from '../../actions/todos.actions'

@Component({
  selector: 'app-todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.css']
})
export class TodoFormComponent implements AfterViewInit {

  @Input('parent') parent
  @ViewChild('input') input: ElementRef
  text

  constructor(private store: Store) {
  }

  submitHandler(e) {
    if(e.key === 'Enter') {
      if(this.text.trim()) {
        this.store.dispatch(add({
          text: this.text,
          parent: this.parent,
          stared: false
        }))
      }
    }
  }

  ngAfterViewInit(): void {
    this.input.nativeElement.focus()
  }

}

<div class="row form">
  <div class="input-field">
    <input placeholder="Add branch...."
           class="materialize-textarea"
           [(ngModel)]="text"
           (keydown)="submitHandler($event)"
           #input
    />
  </div>
</div>

// client/vue-client/src/components/TodoForm.vue
<template>
  <div class="row form">
    <div class="input-field">
      <input placeholder="Add branch...."
             class="materialize-textarea"
             v-model="text"
             @keydown="submitHandler"
             ref="input"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: 'TodoForm',
  props: ['parent'],
  data: () => ({
    text: ''
  }),
  methods: {
    submitHandler(e) {
      if(e.key === 'Enter') {
        this.$store.dispatch('add', {
          text: this.text,
          parent: this.parent
        })
      }
    }
  },
  mounted() {
    this.$refs.input.focus()
  }
}
</script>

<style scoped>
.form .input-field {
  width: 35.8rem !important;
  margin: 0;
}

.form {
  position: relative;
  bottom: 2rem;
  margin: 0;
}
</style>
